-- CreateTable
CREATE TABLE "Question" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "text" TEXT NOT NULL,
    "talkId" INTEGER NOT NULL,
    FOREIGN KEY ("talkId") REFERENCES "Talk" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
